//+------------------------------------------------------------------+
//|                                                  EMA_SAR_MACD_RSI_V2.7.7.12.mq5 |
//|                      Custom Indicator - Momentum & ATR Cross Integration        |
//|                          Copyright 2025, Generated by Code (GPT-5)              |
//+------------------------------------------------------------------+
#property copyright "Aurelio Soares Cortesi"
#property version   "2.7.7.12"
#property indicator_chart_window
#property indicator_buffers 23
#property indicator_plots   23

// --- Inputs principais
input bool UseMomentumCross = true;
input int MomentumPeriodShort = 3;
input int MomentumPeriodLong = 16;

// --- Inputs para ATR Cross
input bool UseATRCross = false;
input int ATRFastPeriod = 3;
input int ATRSlowPeriod = 14;

// --- Buffers
double MomentumShortBuffer[], MomentumLongBuffer[];
double MomentumCrossUpBuffer[], MomentumCrossDownBuffer[];
double ATRFastBuffer[], ATRSlowBuffer[];
double ATRCrossUpBuffer[], ATRCrossDownBuffer[];

// --- Handles
int momentumShortHandle, momentumLongHandle;
int atrFastHandle, atrSlowHandle;

// --- Indexação
#define MOMENTUM_CROSS_UP_INDEX     8
#define MOMENTUM_CROSS_DOWN_INDEX   9
#define ATR_FAST_BUFFER_INDEX       19
#define ATR_SLOW_BUFFER_INDEX       20
#define ATR_CROSS_UP_INDEX          21
#define ATR_CROSS_DOWN_INDEX        22

int OnInit()
{
   if (UseMomentumCross)
   {
      momentumShortHandle = iMomentum(NULL, PERIOD_CURRENT, MomentumPeriodShort, PRICE_CLOSE);
      momentumLongHandle  = iMomentum(NULL, PERIOD_CURRENT, MomentumPeriodLong, PRICE_CLOSE);
   }

   if (UseATRCross)
   {
      atrFastHandle = iATR(NULL, PERIOD_CURRENT, ATRFastPeriod);
      atrSlowHandle = iATR(NULL, PERIOD_CURRENT, ATRSlowPeriod);
   }

   // --- Buffers
   SetIndexBuffer(MOMENTUM_CROSS_UP_INDEX, MomentumCrossUpBuffer, INDICATOR_DATA);
   SetIndexBuffer(MOMENTUM_CROSS_DOWN_INDEX, MomentumCrossDownBuffer, INDICATOR_DATA);
   SetIndexBuffer(ATR_FAST_BUFFER_INDEX, ATRFastBuffer, INDICATOR_DATA);
   SetIndexBuffer(ATR_SLOW_BUFFER_INDEX, ATRSlowBuffer, INDICATOR_DATA);
   SetIndexBuffer(ATR_CROSS_UP_INDEX, ATRCrossUpBuffer, INDICATOR_DATA);
   SetIndexBuffer(ATR_CROSS_DOWN_INDEX, ATRCrossDownBuffer, INDICATOR_DATA);

   return(INIT_SUCCEEDED);
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if (UseMomentumCross)
   {
      CopyBuffer(momentumShortHandle, 0, 0, rates_total, MomentumShortBuffer);
      CopyBuffer(momentumLongHandle, 0, 0, rates_total, MomentumLongBuffer);

      for (int i = rates_total - 2; i >= 0; i--)
      {
         if (MomentumShortBuffer[i] > MomentumLongBuffer[i] && MomentumShortBuffer[i+1] <= MomentumLongBuffer[i+1])
         {
            MomentumCrossUpBuffer[i] = 1;
            MomentumCrossDownBuffer[i] = 0;
         }
         else if (MomentumShortBuffer[i] < MomentumLongBuffer[i] && MomentumShortBuffer[i+1] >= MomentumLongBuffer[i+1])
         {
            MomentumCrossDownBuffer[i] = 1;
            MomentumCrossUpBuffer[i] = 0;
         }
         else
         {
            MomentumCrossUpBuffer[i] = 0;
            MomentumCrossDownBuffer[i] = 0;
         }
      }
   }

   if (UseATRCross)
   {
      CopyBuffer(atrFastHandle, 0, 0, rates_total, ATRFastBuffer);
      CopyBuffer(atrSlowHandle, 0, 0, rates_total, ATRSlowBuffer);

      for (int i = rates_total - 2; i >= 0; i--)
      {
         if (ATRFastBuffer[i] > ATRSlowBuffer[i] && ATRFastBuffer[i+1] <= ATRSlowBuffer[i+1])
         {
            ATRCrossUpBuffer[i] = 1;
            ATRCrossDownBuffer[i] = 0;
         }
         else if (ATRFastBuffer[i] < ATRSlowBuffer[i] && ATRFastBuffer[i+1] >= ATRSlowBuffer[i+1])
         {
            ATRCrossDownBuffer[i] = 1;
            ATRCrossUpBuffer[i] = 0;
         }
         else
         {
            ATRCrossUpBuffer[i] = 0;
            ATRCrossDownBuffer[i] = 0;
         }
      }
   }
   return(rates_total);
}
